version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:qwerty@db:5432/postgres
    command: uvicorn main:app --host 0.0.0.0 --port 80
    healthcheck:
      test: curl -f http://localhost:80/healthcheck || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      web:
        condition: service_healthy
    command: python bot.py

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      # timeout: 10s
      retries: 5
volumes:
  postgres_data: